name: repoman ci
on: [push]
jobs:
  repoman-ci:
    name: repoman ci
    runs-on: ubuntu-latest
    container:
      image: aegypius/repoman
      volumes:
        - /home/runner/work/viperML/viperML-overlay:/overlay
    steps:
      - uses: actions/checkout@v1
      - run: pwd
