name: repoman ci
on: [push]
jobs:
  repoman-ci:
    name: repoman ci
    runs-on: ubuntu-latest
    container:
      image: tastytea/repoman:latest
    steps:
      - run: |
          pwd
          ls
          cat /etc/os-release
      - uses: actions/checkout@v1
      - run: |
          pwd
          ls
          cat /etc/os-release