name: repoman-ci
on: [push, pull_request]
jobs:
  repoman-ci:
    name: repoman-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://tastytea/repoman
        with:
          args: repoman full -Idix
