name: repoman-ci
on:

  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**.skel"

  pull_request:
    branches:
      # TODO temp disabled
      - master

jobs:
  repoman-ci:
    name: repoman-ci
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: docker://tastytea/repoman
        with:
          args: repoman full -Idix
