name: repoman ci
on:
  workflow_dispatch

jobs:
  repoman-ci:
    name: repoman ci
    runs-on: ubuntu-latest
    container:
      image: tastytea/repoman:latest
      volumes:
        - /home/runner/work/viperML/viperML-overlay:/mnt
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls
          cat /etc/os-release