name: repoman ci
on: [push]
jobs:
  repoman-ci:
    name: repoman ci
    runs-on: ubuntu-latest
    container:
      image: tastytea/repoman
      volumes:
        - /home/runner/work/viperML/viperML-overlay:/overlay
    steps:
      - run: repoman --version
