name: repoman ci
on: [push]
jobs:
  repoman-ci:
    name: repoman ci
    runs-on: ubuntu-latest
    container:
      image: tastytea/repoman
      volumes:
        - /home/runner/work/viperML-overlay/viperML-overlay:/overlay
    steps:
      - uses: actions/checkout@v2
      - run: repoman --version
      - run: ls /overlay
